### ISSUE TITLE
Add support for rpyc 5.0.0

### ISSUE THREAD

**Issue by bleykauf** [linien-org/linien#145]
Currently version ==4.1.5 is required. 5.0.0 is not backwards compatible.

**Comment by hermitdemschoenenleben** [comment]
unfortunately right now this isn't possible as rpyc 5 requires python 3.6 and the RedPitaya ecosystem is still at 3.5. I'll keep this open though, hoping that RP base image will get an update

**Comment by qku** [comment]
I would highly appreciate support for rpyc 5.0 as I would like to use linien together with a package already using it.

Let me know if you need help with e. g. testing or so.

**Comment by bleykauf** [comment]
@qku It is very much possible that simply upgrading the version in the `setup.py` of the server and the client and then manually installing these custom version following [these instructions](https://github.com/linien-org/linien/wiki/Development).

**Comment by qku** [comment]
So what works for us is to checkout the `feature/use-rpyc-5` branch on the client and install it, while the server runs normal 0.8.0 (with rpyc < 5.0).

As far as I can tell from my limited experience with linien, everything is working as expected. We are only using linien for a very simple PID setup though, without GUI but interfacing via python from another program.

**Comment by qku** [comment]
Would more testing help you with the upgrade to rpyc 5? We would appreciate an upgrade to facilitate the use of linen together with other packages using rpyc.
