### ISSUE TITLE
Add button to disable sweep temporarily

### ISSUE THREAD

**Issue by bleykauf** [linien-org/linien#181]
Useful for example when observing a beatnote on a spectrum analyzer. Right now you have to disconnect the sweep signal cable.

**Comment by fartmano** [comment]
> Useful for example when observing a beatnote on a spectrum analyzer. Right now you have to disconnect the sweep signal cable.

Would also be nice if one could set the output to a certain value when disabling the sweep. Also useful for intensity stabilization.
