### ISSUE TITLE
Server still not running 

### ISSUE THREAD

**Issue by NekSadam** [linien-org/linien#270]
Hello ! 

After having downloaded the server component and setting up my Red Pitaya (RP) with its host address as suggested, I have an issue with the connection to the RP. 
python keeps trying to run the server but it doesn't seem to be working. 
I tried to use the IP address but it doesn't work either. 

Would you have any suggestion ? 

Thank you !

**Comment by bleykauf** [comment]
Oh, it is closed now, so I guess you fixed the problem?

Some description of how you did that would be much appreciated and might also be useful for other users.

**Comment by bleykauf** [comment]
@NekSadam (just mentioning the user name for possible notification ;) )

**Comment by bleykauf** [comment]
What exactly did you do to fix the issue?

Simply pinging and ssh'ing into the RedPitaya is very unlikely to have any effect whatsoever on the problem.
