### ISSUE TITLE
Sweep speed and error signal ? 

### ISSUE THREAD

**Issue by NekSadam** [linien-org/linien#271]
Hello, 

I am an intern currently working on Doppler-free spectroscopy and as I have been going through your GUI, I came across the Sweep speed setting and I fail to understand what it is meant for. 

Could you please enlighten me ? 

Thank you for your time (and your amazing work on Linien !) !

**Comment by bleykauf** [comment]
The sweep speed is the repetition rate of the triangular  sweep used for scanning the lasers frequency. You can for  example observe this on an oscilloscope.

Please note that these kind of questions after better suited for the [discussion](https://github.com/linien-org/linien/discussions/categories/q-a) section. I will soon make this clearer, see #273.
