### ISSUE TITLE
Weird behaviour of slow integrator for very low strength

### ISSUE THREAD

**Issue by fartmano** [linien-org/linien#288]
For very low strength (e.g. 1), the slow integrator is jumping in strange ways (see screenshot). With higher strength it works as expected.

Using version 0.5.3. of Linien.

![image](https://user-images.githubusercontent.com/33025029/194520093-e873f61e-6b8e-472a-b775-dda1822f4878.png)

**Comment by bleykauf** [comment]
Added a note that larger values should be used for stable operation  in 94ced1e. Closed.
