### ISSUE TITLE
Use systemd for running server

### ISSUE THREAD

**Issue by bleykauf** [linien-org/linien#293]
As suggested by @doronbehar in https://github.com/linien-org/linien/pull/277#issuecomment-1272506334.

**Comment by doronbehar** [comment]
> One benefit of the current system is that it is easy to look at the running server with screen. Is something similar possible with systemd?

Yes! As pointed out in https://github.com/linien-org/linien/pull/277#issuecomment-1272506334 : Using `journalctl --unit=linien.service`. Adding `--follow` would show you live the stderr and stdout `linien-server` prints.

**Comment by doronbehar** [comment]
This can be closed too now since 2.0.
